export const mockJourneys = [
  {
    id: "mock-ic5757-2026-05-05",
    source: "mock",
    confidence: 0.82,
    train_number: "IC 5757",
    service_name: "InterCity",
    line_name: "IC 5757",
    product: "IC",
    operator_code: "DSB",
    operator_name: "Danish State Railways",
    infrastructure_manager: null,
    origin_station_name: "Kobenhavn H",
    origin_station_code: "8601309",
    destination_station_name: "Flensburg",
    destination_station_code: "8000103",
    planned_departure_at: "2026-05-05T08:22:00+02:00",
    estimated_departure_at: "2026-05-05T08:22:00+02:00",
    actual_departure_at: null,
    planned_arrival_at: "2026-05-05T11:53:00+02:00",
    estimated_arrival_at: "2026-05-05T11:53:00+02:00",
    actual_arrival_at: null,
    departure_delay_minutes: 0,
    arrival_delay_minutes: 0,
    status: "planned",
    platform_planned: "5",
    platform_actual: "5",
    cancelled_section_from: null,
    cancelled_section_to: null,
    calling_points: [],
    disruption_reason_public: null,
    disruption_reason_code: null,
    remarks: [],
    raw: {
      provider_hint: "mock",
      leg_count: 2,
      rail_leg_count: 2,
      transfer_count: 1,
      has_connections: true,
      has_replacement: false
    }
  },
  {
    id: "mock-ec395-2026-05-04",
    source: "mock",
    confidence: 0.85,
    train_number: "EC 395",
    service_name: "EuroCity",
    line_name: "EC 395",
    product: "EC",
    operator_code: "DSB/DB",
    operator_name: "DSB / Deutsche Bahn",
    origin_station_name: "Kobenhavn H",
    origin_station_code: "8601309",
    destination_station_name: "Hamburg Hbf",
    destination_station_code: "8002549",
    planned_departure_at: "2026-05-04T08:22:00+02:00",
    estimated_departure_at: "2026-05-04T08:37:00+02:00",
    actual_departure_at: null,
    planned_arrival_at: "2026-05-04T13:02:00+02:00",
    estimated_arrival_at: "2026-05-04T14:12:00+02:00",
    actual_arrival_at: null,
    departure_delay_minutes: 15,
    arrival_delay_minutes: 70,
    status: "delayed",
    platform_planned: "7",
    platform_actual: "7",
    cancelled_section_from: null,
    cancelled_section_to: null,
    calling_points: [],
    disruption_reason_public: "Delay from earlier section",
    disruption_reason_code: null,
    remarks: ["Delay from earlier section"],
    raw: {
      provider_hint: "mock",
      leg_count: 1,
      rail_leg_count: 1,
      transfer_count: 0,
      has_connections: false,
      has_replacement: false
    }
  },
  {
    id: "mock-ic413-2026-05-06",
    source: "mock",
    confidence: 0.84,
    train_number: "IC 413",
    service_name: "InterCity",
    line_name: "IC 413",
    product: "IC",
    operator_code: "DSB",
    operator_name: "Danish State Railways",
    infrastructure_manager: null,
    origin_station_name: "Kobenhavn H",
    origin_station_code: "8600626",
    destination_station_name: "Aalborg",
    destination_station_code: "8600086",
    planned_departure_at: "2026-05-06T08:10:00+02:00",
    estimated_departure_at: "2026-05-06T08:18:00+02:00",
    actual_departure_at: null,
    planned_arrival_at: "2026-05-06T13:06:00+02:00",
    estimated_arrival_at: "2026-05-06T13:34:00+02:00",
    actual_arrival_at: null,
    departure_delay_minutes: 8,
    arrival_delay_minutes: 28,
    status: "delayed",
    platform_planned: "4",
    platform_actual: "4",
    cancelled_section_from: null,
    cancelled_section_to: null,
    calling_points: [],
    disruption_reason_public: "Forsinkelse fra tidligere strækning",
    disruption_reason_code: null,
    remarks: ["Forsinkelse fra tidligere strækning"],
    raw: {
      provider_hint: "mock",
      leg_count: 1,
      rail_leg_count: 1,
      transfer_count: 0,
      has_connections: false,
      has_replacement: false
    }
  }
];
