<?php
declare(strict_types=1);

return [
    'Kobenhavn H' => [
        'Kobenhavn H',
        'Koebenhavn H',
        'Kbh H',
        'Kbh',
        'København H',
        'Kobenhavn Hovedbanegard',
        'Kobenhavn Hovedbanegaard',
        'Kobenhavns Hovedbanegard',
        'Kobenhavns Hovedbanegaard',
        'København Hovedbanegård',
        'Københavns Hovedbanegård',
        'Copenhagen H',
        'Copenhagen Central Station',
    ],
    'Aarhus H' => [
        'Aarhus H',
        'Århus H',
        'Aarhus Hovedbanegard',
        'Aarhus Hovedbanegaard',
        'Århus Hovedbanegård',
        'Aarhus Central Station',
    ],
    'Odense' => [
        'Odense',
        'Odense st',
        'Odense Station',
        'Odense Banegard',
        'Odense Banegaard',
    ],
    'Aalborg' => [
        'Aalborg',
        'Aalborg st',
        'Aalborg Station',
        'Aalborg Banegard',
        'Aalborg Banegaard',
        'Aalborg St.',
        'Ålborg',
        'Ålborg st',
        'Ålborg Station',
    ],
    'Flensburg' => [
        'Flensburg',
        'Flensborg',
        'Flensburg / Flensborg',
        'Flensburg Hbf',
        'Flensburg Station',
    ],
    'Hamburg Hbf' => [
        'Hamburg Hbf',
        'Hamburg Hauptbahnhof',
        'Hamburg Central Station',
    ],
    'Berlin Hbf' => [
        'Berlin Hbf',
        'Berlin Hauptbahnhof',
        'Berlin Central Station',
    ],
    'Koln Hbf' => [
        'Koln Hbf',
        'Köln Hbf',
        'Koeln Hbf',
        'Koln Hauptbahnhof',
        'Köln Hauptbahnhof',
        'Cologne Central Station',
    ],
    'Malmo C' => [
        'Malmo C',
        'Malmö C',
        'Malmo Central',
        'Malmö Centralstation',
        'Malmo Centralstation',
    ],
    'Goteborg C' => [
        'Goteborg C',
        'Göteborg C',
        'Goteborg Central',
        'Göteborg Central',
        'Göteborg Centralstation',
        'Gothenburg Central',
    ],
    'Stockholm C' => [
        'Stockholm C',
        'Stockholm Central',
        'Stockholm Centralstation',
    ],
    'Oslo S' => [
        'Oslo S',
        'Oslo Central',
        'Oslo Sentralstasjon',
    ],
    'Zurich HB' => [
        'Zurich HB',
        'Zürich HB',
        'Zurich Main Station',
    ],
    'Wien Hbf' => [
        'Wien Hbf',
        'Vienna Central Station',
        'Wien Hauptbahnhof',
    ],
];
